import cv2
image =cv2.imread("E:\\programming\\sketch\\tiger.jpg")
grey_filter = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
invert = cv2.bitwise_not(grey_filter)
blur = cv2.GaussianBlur(invert,(21,21),0)
invertedblur = cv2.bitwise_not(blur)
sketch_filter =cv2.divide(grey_filter,invertedblur,scale=256.0)
cv2.imwrite("original_image.jpg",image)
cv2.imwrite("grey_image.jpg",invert)
cv2.imwrite("blur_image.jpg",blur)
cv2.imwrite("invertedblur.jpg",invertedblur)
cv2.imwrite("skecth_image.jpg",sketch_filter)
cv2.imshow("original_image",image)
cv2.imshow("grey_image",invert)
cv2.imshow("blur_image",blur)
cv2.imshow("invertedblur",invertedblur)
cv2.imshow("skecth_image",sketch_filter)
cv2.waitKey(0)